### PR TITLE
Enable source build

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by dagood** [comment]
The container init problem is probably https://github.com/dotnet/source-build/issues/1795. I think this can wait until we fix in on the dotnet/arcade side.

**Comment by dagood** [comment]
It looks like once this repo gets an Arcade SDK `>= 6.0.0-beta.21064.7`, this will work. (After changing from `runSourceBuild` -> `enableSourceBuild` and removing `sourceBuildParameters`.) It went green when I tried a manual upgrade at https://github.com/dotnet/sourcelink/pull/692.

I also kicked off internal build on a dev branch to look ahead for build errors there.

**Comment by dagood** [comment]
> I also kicked off internal build on a dev branch to look ahead for build errors there.

It hit issues in signing validation. 😕 It recursively looked at the nupkgs within the source-build intermediate nupkg and saw they're unsigned. At first glance it wouldn't make sense to me to actually sign these inner nupkgs. I'll look into this.

**Comment by tmat** [comment]
@dagood Is this still relevant?

**Comment by dagood** [comment]
Thanks for checking--it can be closed. I included the commit in https://github.com/dotnet/sourcelink/pull/692 which has already been merged.

**Pull request closed without merging**
