### PR TITLE
Update LibGit to 0.26.2

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by bording** [comment]
@tmat I recommend using the latest 0.27 preview instead. Lots of progress on native binaries that get shipped to increase compatibility.

**Comment by tmat** [comment]
We would like to use a stable version. It's just for testing.

**Comment by tmat** [comment]
Superseded by https://github.com/dotnet/sourcelink/pull/778.

@bording
Turns out 0.27 preview was needed to run on the latest Ubuntu image we have.

**Pull request closed without merging**
