### PR TITLE
GH-576: Fix relative submodule URL handling.

### PR DESCRIPTION
**Pull request by Zastai**
They should be resolved against the main repository's URL, not the working directory.

### CODE REVIEW

**Comment by Zastai** [comment]
An alternative might be to ignore the URL in .gitmodules, and instead use the branch specification to get the repository url from the module's own config file, if it exists.

**Comment by Zastai** [comment]
Currently I essentially inlined a NormalizeUrl overload, tweaking the root path argument.
It may be more desirable to create another overload (or a NormalizeSubmoduleUrl() method) instead.

**Comment by Zastai** [comment]
(Update: restored accidentally-removed whitespace, and corrected the issue name in a comment.)

**Comment by tmat** [comment]
Thanks for the proposed change. I see what the problem is now. I think however that we need to check `submodule.<name>.url` configuration variable to find the URL for the submodule (see https://git-scm.com/docs/gitsubmodules). This variable is calculated based on the entry in `.gitmodules` by `git submodule init` and will be present for initialized submodules. We can skip uninitialized submodules as they won't have source code contributing to the build anyways. I'm gonna send a PR implementing this approach.

**Comment by tmat** [comment]
Superseded by https://github.com/dotnet/sourcelink/pull/587.

**Pull request closed without merging**
