### PR TITLE
Remove obsolete build properties

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
Official test https://dev.azure.com/dnceng/internal/_build/results?buildId=2224808&view=results

**Comment by tmat** [comment]
Awesome. Thanks!

**Comment by tmat** [comment]
The linked official build failed:

```
The "PublishSymbols" task was not given a value for the required parameter "PersonalAccessToken"
```

Is there another one?

**Comment by mmitche** [comment]
@tmat https://dev.azure.com/dnceng/internal/_build/results?buildId=2224832&view=results

**Pull request merged**
