### PR TITLE
WIP: dotnet-sourcelink tool

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by NikolaMilosavljevic** [comment]
@tmat would it be possible to have an option to not check for target of the source-link, and only check for presence of the link in PDB file? For source-build offline scenario we would only need to check the presence of the link, but for online build, it is very valuable to check for link and the target of the link.

**Comment by tmat** [comment]
@NikolaMilosavljevic Sure feel free to send PR once this is merged.

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic Sure feel free to send PR once this is merged.

@tmat when do we expect this PR to be merged?

**Comment by tmat** [comment]
@NikolaMilosavljevic Done. SOrry for the delay.

**Pull request merged**
